# This is a basic workflow to help you get started with Actions

name: CL

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
   # branches: [ "main" ]
 # pull_request:
 #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      inputs:
        mensagem:
          type: string
          required: true
        cafe:
           type: boolean
           description: Vamos tomar cafe
        ambiente:
           type: environment
        nuvem:
            type: choice
            description: Escolha o comando com que pretende trabalhar
            options: 
             - ssh
             - scp
             - sql
             - fcp
             
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-aws-workflow:
    if: ${{ github.event.inputs.comando }} == 'ssh' 
    uses: ./.github/workflows/ssh.yml
    with:
      msg : ${{ github.event.inputs.mensagem }}
    secrets: inherit
  call-azure-workflow:
    if: ${{ github.event.inputs.comando }} == 'scp' 
    uses: ./.github/workflows/scp.yml
    with:
      msg : ${{ github.event.inputs.comando }}
    secrets: inherit
  call-gcp-workflow:
    if: ${{ github.event.inputs.comando }} == 'sql' 
    uses: ./.github/workflows/sql.yml
    with:
      msg : ${{ github.event.inputs.mensagem }}
    secrets: inherit
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo ${{ github.events.inputs.mensagem }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ${{ github.events.inputs.cafe }}
          echo test, and deploy your project
          
          
